services:
  gouda:
    container_name: gouda-local
    image: ras334/gouda:local
    build:
      context: .
    ports:
      - "9862:9862"
    environment:
      - GOUDA_USERNAME=admin
      - GOUDA_PASS=admin
      - GOUDA_UID=1000
      - GOUDA_GID=1000
      - GOUDA_DOWNLOAD_DIR=/media/downloads
      - GOUDA_COMPLETE_DIR=/media/complete
      - GOUDA_TORRENT_DIR=/media/downloads/torrents
    volumes:
      - D:\Dev\Go\mam\gouda\sample:/media
      - D:\Dev\Go\mam\gouda\sample\config:/appdata/config
    profiles:
      - ""
      - local
      - gou

  tprv:
    container_name: transmissionpriv
    image: lscr.io/linuxserver/transmission:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - USER=admin
      - PASS=admin
      - PEERPORT=9161
    volumes:
      - D:\Dev\Go\mam\gouda\sample:/media
    ports:
      - "9092:9091"
      - "9161:9161"
    restart: unless-stopped
    profiles:
      - gou
      - tor
      - ""
      - main

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8722
      - TORRENTING_PORT=6881
    ports:
      - "8722:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
    profiles:
      - qbit

  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    ports:
      - "8112:8112"
      - "17693:17693"
      - "17693:17693/udp"
      - "58846:58846" #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped
    profiles:
      - delug
