# This is a example docker compose file that can be used in your setup
services:
  gouda:
    container_name: gouda
    image: ras334/gouda:latest
    build:
      context: .
    ports:
      - "9862:9862"
    environment:
      - GOUDA_USERNAME=admin
      - GOUDA_PASS=admin
      - GOUDA_UID=1000
      - GOUDA_GID=1000
      - GOUDA_DOWNLOAD_DIR=/media/downloads
      - GOUDA_DEFAULT_DIR=/media/complete
      - GOUDA_TORRENT_DIR=/media/downloads/torrents
    volumes:
      - /path/to/media:/media # make sure this matches your download client mount exactly
      - /path/to/config:/config

  # transmission users
  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - USER=admin
      - PASS=admin
      - PEERPORT=9262
    volumes:
      - /path/to/media:/media # make sure this matches gouda mount exactly
      - /path/to/config:/config
    ports:
      - "9092:9091"
      - "9161:9161"
    restart: unless-stopped

  # qbit users
  qbit:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=9262
    volumes:
      - /path/to/media:/media # make sure this matches gouda mount exactly
      - /path/to/qbittorrent/appdata:/config
    ports:
      - "8080:8080"
      - "9262:9262"
      - "9262:9262/udp"
    restart: unless-stopped
