services:
  transmissionprivate:
    container_name: transmissionpriv
    image: lscr.io/linuxserver/transmission:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - USER=admin
      - PASS=admin
      - PEERPORT=9161
    volumes:
      - D:\Dev\Go\mam\gouda\sample:/media
      - D:\Dev\Go\mam\gouda\sample\transmission\config:/config
    ports:
      - "9092:9091"
      - "9161:9161"
    restart: unless-stopped

  gouda:
    container_name: gouda
    image: ras334/gouda:latest
    build:
      context: .
    ports:
      - "9862:9862"
    environment:
      - GOUDA_UID=1000
      - GOUDA_GID=1000
      - GOUDA_DOWNLOAD_DIR=/media/downloads
      - GOUDA_DEFAULT_DIR=/media/complete
      - GOUDA_TORRENT_DIR=/media/downloads/torrents
    env_file:
      - .env
    volumes:
      - D:\Dev\Go\mam\gouda\sample:/media
      - D:\Dev\Go\mam\gouda\sample\config:/appdata/config