# .circleci/config.yml
version: 2.1

orbs:
  android: circleci/android@2.3.0

workflows:
  build-and-release:
    jobs:
      - build-flutter-android:
          filters:
            branches:
              only: main

jobs:
  build-flutter-android:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2023.07.1

    steps:
      - checkout

      - run:
          name: Install Flutter
          command: |
            cd /opt
            sudo git clone https://github.com/flutter/flutter.git -b stable
            echo 'export PATH="$PATH:/opt/flutter/bin"' >> $BASH_ENV
            source $BASH_ENV
            flutter doctor

      - run:
          name: Flutter Dependencies
          command: |
            flutter pub get

      - run:
          name: Build Flutter APK
          command: |
            flutter build apk --release

      - run:
          name: Create or Update Canary Release
          command: |
            # Install GitHub CLI
            sudo apt-get update
            sudo apt-get install -y gh
            
            # Authenticate with GitHub
            echo "$GITHUB_TOKEN" | gh auth login --with-token
            
            # Set repository context
            export REPO="${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
            
            # Delete existing canary release and tag if they exist
            gh release delete canary --repo $REPO --yes || true
            git push --delete origin canary || true
            
            # Create new canary tag and release
            git tag canary
            git push origin canary
            
            # Create the release with APK
            gh release create canary \
              --repo $REPO \
              --title "Canary Build" \
              --notes "Latest canary build from main branch ($(date))" \
              --prerelease \
              build/app/outputs/flutter-apk/app-release.apk
          environment:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - store_artifacts:
          path: build/app/outputs/flutter-apk/
          destination: apk