version: 2.1

jobs:
  build-amd64:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - checkout
      - run:
          name: "Build AMD64 Docker Image"
          command: |
            IMAGE_NAME=ghcr.io/${GITHUB_USERNAME}/gouda:build-linux
            docker build --platform linux/amd64 -t ${IMAGE_NAME}:${CIRCLE_SHA1}-amd64 .
      - run:
          name: "Login to GitHub Container Registry"
          command: echo "$GITHUB_TOKEN" | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
      - run:
          name: "Push AMD64 Image"
          command: |
            IMAGE_NAME=ghcr.io/${GITHUB_USERNAME}/gouda:build-linux
            docker push ${IMAGE_NAME}:${CIRCLE_SHA1}-amd64

  build-arm64:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: "Build ARM64 Docker Image"
          command: |
            IMAGE_NAME=ghcr.io/${GITHUB_USERNAME}/gouda:build-linux
            docker build --platform linux/arm64 -t ${IMAGE_NAME}:${CIRCLE_SHA1}-arm64 .
      - run:
          name: "Login to GitHub Container Registry"
          command: echo "$GITHUB_TOKEN" | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
      - run:
          name: "Push ARM64 Image"
          command: |
            IMAGE_NAME=ghcr.io/${GITHUB_USERNAME}/gouda:build-linux
            docker push ${IMAGE_NAME}:${CIRCLE_SHA1}-arm64

  create-manifest:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: "Login to GitHub Container Registry"
          command: echo "$GITHUB_TOKEN" | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
      - run:
          name: "Create and Push Multi-Arch Manifest"
          command: |
            IMAGE_NAME=ghcr.io/${GITHUB_USERNAME}/gouda:build-linux
            
            # Create manifest for commit SHA
            docker manifest create ${IMAGE_NAME}:${CIRCLE_SHA1} \
              ${IMAGE_NAME}:${CIRCLE_SHA1}-amd64 \
              ${IMAGE_NAME}:${CIRCLE_SHA1}-arm64
            docker manifest push ${IMAGE_NAME}:${CIRCLE_SHA1}
            
            # Create manifest for latest tag
            docker manifest create ${IMAGE_NAME}:latest \
              ${IMAGE_NAME}:${CIRCLE_SHA1}-amd64 \
              ${IMAGE_NAME}:${CIRCLE_SHA1}-arm64
            docker manifest push ${IMAGE_NAME}:latest

workflows:
  build-workflow:
    jobs:
      - build-amd64
      - build-arm64
      - create-manifest:
          requires:
            - build-amd64
            - build-arm64