set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

# generate and copy out go files and remove go generated dir
gen:
    just build
    docker run --rm -v "{{justfile_directory()}}:/workspace" gouda-proto:latest
    just go
    just dart
    just web

go:
    clear
    echo 'moving go files'
    rm -r ../src/generated/*
    cp -r generated/go/* ../src/generated/
    rm -r generated/go

dart:
    clear
    echo 'moving dart files'
    rm -r ../brie/lib/gen/*
    cp -r generated/dart/* ../brie/lib/gen/
    rm -r generated/dart

web:
    clear
    echo 'moving web files'
    rm -r ../parmesan/source/gen/*
    cp -r generated/web/* ../parmesan/source/gen/
    rm -r generated/web


# drop into a shell and interact with the image
# CTRL+D to exit
it:
    just build
    docker run --rm --name gouda_grpc_shell -v "{{justfile_directory()}}:/workspace" -it gouda-proto:latest /bin/bash

# build image
build:
	docker build . -t gouda-proto:latest

# build and push
bpsh:
	make build
	make push
