set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

# generate and copy out go files and remove go generated dir
gen:
    just build
    docker run --rm -v "{{justfile_directory()}}:/workspace" gouda-proto:latest
    rm -r ../src/generated/*
    cp -r generated/go/* ../src/generated/
    rm -r generated/go

# drop into a shell and interact with the image
# CTRL+D to exit
it:
    just build
    docker run --rm --name gouda_grpc_shell -v "{{justfile_directory()}}:/workspace" -it gouda-proto:latest /bin/bash

# build image
build:
	docker build . -t gouda-proto:latest

# build and push
bpsh:
	make build
	make push

#remove-dir dir:
#    #!/usr/bin/env sh
#    {{if os_family() == "windows"}}
#        rd /s /q "{{dir}}" 2>NUL || exit 0
#    {{else}}
#        rm -rf "{{dir}}"
#    {{endif}}