name: Dev Docker Build

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - brie/**
      - core/**
      - Dockerfile
      - .github/workflows/dev-docker.yml
      - .github/workflows/action-gouda-docker.yml

permissions:
  contents: write   # To checkout the repository
  packages: write  # To push Docker images to GHCR

jobs:
  build-docker:
    name: Build docker dev build
    uses: ./.github/workflows/action-gouda-docker.yml
    with:
      source_branch: ${{ github.ref_name }}
    secrets: inherit
