name: Release Pipeline

on:
  push:
    branches:
      - main # publish a dev build on main
    paths: # trigger only when source code changes
      - .github/workflows/dev.yml
      - .github/workflows/action-gouda-docker.yml
      - goub/**
      - brie/**
      - parmesan/**
      - src/**

permissions:
  contents: write   # To checkout the repository
  packages: write  # To push Docker images to GHCR


jobs:
  build-docker:
    name: Build docker dev build
    uses: ./.github/workflows/action-gouda-docker.yml
    with:
      source_branch: ${{ github.ref_name }}
    secrets: inherit

  build_and_release_linux:
    name: Build and Release for Linux
    uses: ./.github/workflows/action-gouda-native.yml
    with:
      os: ubuntu-latest
      flutter_version: '3.27.1'
      go_version: '1.24'
      tag_name: dev
    secrets: inherit