name: Release Build

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'The tag name to use for the release (e.g., v1.0.0). Required if manually dispatched.'
        required: true
        type: string

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  build-docker:
    name: Build and Release for Docker
    uses: ./.github/workflows/action-gouda-docker.yml
    with:
      version_tag: ${{ github.event.inputs.tag_name }}
      is_latest: true
      source_branch: ${{ github.ref_name }}
    secrets: inherit

  build_and_release_linux:
    name: Gouda Linux Build
    uses: ./.github/workflows/action-gouda-native.yml
    with:
      os: ubuntu-latest
      tag_name: ${{ github.event.inputs.tag_name }}
    secrets: inherit

  build_and_release_windows:
    name: Gouda Windows Build
    uses: ./.github/workflows/action-gouda-native.yml
    with:
      os: windows-latest
      tag_name: ${{ github.event.inputs.tag_name }}
    secrets: inherit
